import { readFileSync, writeFileSync } from "node:fs";

export interface SwaggerParam {
  name: string;
  in: string;
  required?: boolean;
  type?: string;
}

export interface SwaggerOperation {
  parameters?: SwaggerParam[];
}

export interface SwaggerSpec {
  paths: Record<string, { post?: SwaggerOperation }>;
}

export interface EndpointParam {
  name: string;
  required: boolean;
  type: string;
}

export interface EndpointDef {
  key: string;
  path: string;
  params: EndpointParam[];
}

function toCamelSegment(segment: string): string {
  return segment
    .split(/[_-]/)
    .map((part, i) => (i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join("");
}

export function pathToKey(apiPath: string): string {
  const segments = apiPath.replace(/^\//, "").split("/");
  return segments
    .map((segment, i) => {
      const camel = toCamelSegment(segment);
      return i === 0
        ? camel.charAt(0).toLowerCase() + camel.slice(1)
        : camel.charAt(0).toUpperCase() + camel.slice(1);
    })
    .join("");
}

export function extractEndpoints(spec: SwaggerSpec): EndpointDef[] {
  const paths = Object.keys(spec.paths).sort();
  return paths
    .filter((apiPath) => spec.paths[apiPath].post)
    .map((apiPath) => {
      const params = (spec.paths[apiPath].post!.parameters ?? []).map((p) => ({
        name: p.name,
        required: p.required ?? false,
        type: p.type ?? "object",
      }));
      return { key: pathToKey(apiPath), path: apiPath, params };
    });
}

function render(endpoints: EndpointDef[]): string {
  const entries = endpoints
    .map((e) => {
      const params = e.params
        .map((p) => `{ name: ${JSON.stringify(p.name)}, required: ${p.required}, type: ${JSON.stringify(p.type)} }`)
        .join(", ");
      return `  { key: ${JSON.stringify(e.key)}, path: ${JSON.stringify(e.path)}, params: [${params}] },`;
    })
    .join("\n");

  return `// AUTO-GENERATED by scripts/generate-client.ts — do not edit by hand.
// Regenerate with: npm run generate

export interface EndpointParam {
  name: string;
  required: boolean;
  type: string;
}

export interface EndpointDef {
  key: string;
  path: string;
  params: EndpointParam[];
}

export const ENDPOINTS = [
${entries}
] as const satisfies readonly EndpointDef[];

export type EndpointKey = (typeof ENDPOINTS)[number]["key"];
`;
}

function main(): void {
  const specPath = new URL("../spec/buchhaltungsbutler-v1.json", import.meta.url);
  const spec: SwaggerSpec = JSON.parse(readFileSync(specPath, "utf-8"));
  const endpoints = extractEndpoints(spec);
  const outPath = new URL("../src/bb-client/generated/endpoints.ts", import.meta.url);
  writeFileSync(outPath, render(endpoints));
  console.log(`Generated ${endpoints.length} endpoints to src/bb-client/generated/endpoints.ts`);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
